version: '3.8'
##### Note: this docker-compose project is for development purposes ######

x-xx-common-services-settings: &common-settings
  restart: always

services:
  prometheus:
    <<: *common-settings
    image: aleskandro/prometheus:master
    volumes:
      - ../examples/alibaba/output:/prometheus
    ports:
      - 9090:9090
